"""create_flow_task_model

Revision ID: 40e90eca5ce8
Revises: 9ec59b98733d
Create Date: 2026-05-16 18:14:53.746354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e90eca5ce8'
down_revision: Union[str, Sequence[str], None] = '9ec59b98733d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_task',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_start_task', sa.Boolean(), nullable=False),
    sa.Column('flow_uuid', sa.UUID(), nullable=False),
    sa.Column('task_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flow_uuid'], ['flow.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_uuid'], ['task.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('task_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_task')
    # ### end Alembic commands ###
