"""create_condition_model

Revision ID: cae3fb812890
Revises: 40e90eca5ce8
Create Date: 2026-05-16 18:44:59.654681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae3fb812890'
down_revision: Union[str, Sequence[str], None] = '40e90eca5ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_task',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('flow_uuid', sa.UUID(), nullable=False),
    sa.Column('source_task_uuid', sa.UUID(), nullable=False),
    sa.Column('target_task_success', sa.UUID(), nullable=False),
    sa.Column('target_task_failure', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['flow_uuid'], ['flow.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_uuid'], ['task.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_task_failure'], ['task.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_task_success'], ['task.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('source_task_uuid', 'target_task_success', 'target_task_failure')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_task')
    # ### end Alembic commands ###
