"""add_type_field_to_task

Revision ID: dcac7801e72a
Revises: cae3fb812890
Create Date: 2026-05-17 17:17:23.769535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcac7801e72a'
down_revision: Union[str, Sequence[str], None] = 'cae3fb812890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('only_one_start_task_per_flow_allowed', 'flow_task', ['flow_uuid'], unique=True, postgresql_where=sa.text('is_start_task IS true'))
    op.add_column('task', sa.Column('type', sa.String(), nullable=False,server_default="fetch"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'type')
    op.drop_index('only_one_start_task_per_flow_allowed', table_name='flow_task', postgresql_where=sa.text('is_start_task IS true'))
    # ### end Alembic commands ###
